export const TypesObj = {
  grass: 'tourquoise',
  fire: 'red',
  water: 'blue',
  bug: 'green',
  normal: 'brown',
  poison: 'purple',
  electric: 'yelow',
  ground: 'orange',
  fairy: 'pink',
  fighting: 'fuchsia',
  psychic: 'crimson',
  rock: 'gray',
  ghost: 'silver',
  ice: 'skyblue',
  dragon: 'darkgray',
}
export const OnlyTypesObj = [
  'grass',
  'fire',
  'water',
  'bug',
  'normal',
  'poison',
  'electric',
  'ground',
  'fairy',
  'fighting',
  'psychic',
  'rock',
  'ghost',
  'ice',
  'dragon',
]
